// packages/styleguide-viewer/src/components/DeviceControls.tsx
import type { ChangeEvent } from 'react'
import { cx } from '../utils'

export type Device = 'mobile' | 'tablet' | 'desktop' | 'custom'
export type DeviceBreakpoints = Record<Device, number>

interface DeviceControlsProps {
  previewWidth: number
  customWidth: number
  selectedDevice: Device
  onSelect: (device: Device) => void
  onCustomWidthChange: (width: number) => void
  onApply: () => void
}

export function DeviceControls({
  previewWidth,
  customWidth,
  selectedDevice,
  onSelect,
  onCustomWidthChange,
  onApply,
}: DeviceControlsProps) {
  function handleCustomWidthChange(event: ChangeEvent<HTMLInputElement>) {
    onCustomWidthChange(Number(event.target.value))
  }

  return (
    <div className="device-controls">
      <div className="device-controls__group">
        <button className={deviceButtonClass(selectedDevice, 'mobile')} onClick={() => onSelect('mobile')}>
          mobile
        </button>
        <button className={deviceButtonClass(selectedDevice, 'tablet')} onClick={() => onSelect('tablet')}>
          tablet
        </button>
        <button className={deviceButtonClass(selectedDevice, 'desktop')} onClick={() => onSelect('desktop')}>
          desktop
        </button>
      </div>
      <span className="label">custom:</span>
      <input
        className="device-controls__input"
        type="number"
        value={customWidth}
        onChange={handleCustomWidthChange}
      />
      <button className={deviceButtonClass(selectedDevice, 'custom')} onClick={onApply}>
        apply
      </button>
      <span className="px">{previewWidth}px</span>
    </div>
  )
}

function deviceButtonClass(selectedDevice: Device, device: Device) {
  return cx('device-controls__button', selectedDevice === device && 'device-controls__button--active')
}

// packages/styleguide-lib/src/core/components/DeviceControls.vue
<template>
  <div class="device-controls">
    <div class="device-controls__group">
      <button
        :class="['device-controls__button', { 'device-controls__button--active': props.selectedDevice === 'mobile' }]"
        @click="emit('select', 'mobile')"
      >mobile</button>
      <button
        :class="['device-controls__button', { 'device-controls__button--active': props.selectedDevice === 'tablet' }]"
        @click="emit('select', 'tablet')"
      >tablet</button>
      <button
        :class="['device-controls__button', { 'device-controls__button--active': props.selectedDevice === 'desktop' }]"
        @click="emit('select', 'desktop')"
      >desktop</button>
    </div>
    <span class="label">custom:</span>
    <input class="device-controls__input" type="number" :value="props.customWidth" @input="handleCustomWidthChange" />
    <button
      :class="['device-controls__button', { 'device-controls__button--active': props.selectedDevice === 'custom' }]"
      @click="emit('apply')"
    >apply</button>
    <span class="px">{{ props.previewWidth }}px</span>
  </div>
</template>

<script lang="ts" setup>
import { withDefaults, defineProps, defineEmits } from 'vue';
import type { Device } from '../composables/useDevicePreview';

const props = withDefaults(defineProps<{
  previewWidth: number;
  customWidth: number;
  selectedDevice: Device;
}>(), {});

const emit = defineEmits<{
  (e: 'select', device: Device): void;
  (e: 'update:customWidth', width: number): void;
  (e: 'apply'): void;
}>();

function handleCustomWidthChange(event: Event) {
  const target = event.target as HTMLInputElement;
  const value = Number(target.value);
  emit('update:customWidth', value);
}
</script>
