// packages/styleguide-viewer/src/components/StyleguideContainer.tsx
import { useEffect, useMemo, useState } from 'react'
import type { ComponentDocsSource, NormalizedComponentDoc } from 'styleguide-schema'
import { createRendererRegistry, normalizeDocs, type StyleguideRendererAdapter } from 'styleguide-core'
import { createDefaultRendererAdapter } from '../renderer'
import type { Device } from './DeviceControls'
import { WidgetComponentDoc } from './WidgetComponentDoc'
import { cx } from '../utils'

interface StyleguideContainerProps {
  docs?: ComponentDocsSource
  renderers?: StyleguideRendererAdapter[]
  deviceBreakpoints?: Record<Exclude<Device, 'custom'>, number>
}

export function StyleguideContainer({
  docs,
  renderers = [],
  deviceBreakpoints,
}: StyleguideContainerProps) {
  const [activeDocIndex, setActiveDocIndex] = useState(0)
  const effectiveDocs = useMemo(() => normalizeStyleguideDocs(docs), [docs])
  const activeDoc = effectiveDocs[activeDocIndex] ?? effectiveDocs[0]
  const rendererRegistry = useMemo(() => {
    return createRendererRegistry([createDefaultRendererAdapter(), ...renderers])
  }, [renderers])

  useEffect(() => {
    if (effectiveDocs.length === 0 || activeDocIndex >= effectiveDocs.length) {
      setActiveDocIndex(0)
    }
  }, [activeDocIndex, effectiveDocs.length])

  return (
    <div className="styleguide-container">
      {effectiveDocs.length > 0 && (
        <nav className="styleguide-nav">
          <p className="styleguide-nav-label">Components</p>
          <div className="nav-tabs">
            {effectiveDocs.map((doc, index) => (
              <button
                key={`${doc.id}-${index}`}
                className={cx('nav-tab', activeDocIndex === index && 'nav-tab--active')}
                onClick={() => setActiveDocIndex(index)}
              >
                <span className="nav-tab-dot" aria-hidden="true"></span>
                <span className="nav-tab-copy">
                  <span className="nav-tab-title">{doc.title}</span>
                </span>
              </button>
            ))}
          </div>
        </nav>
      )}

      <main className="styleguide-content">
        {effectiveDocs.length === 0 ? (
          <div className="no-docs">
            <h2>문서가 없습니다</h2>
            <p>문서를 추가해주세요. (로드된 문서: 0개)</p>
          </div>
        ) : (
          activeDoc && (
            <WidgetComponentDoc
              component={activeDoc.component}
              deviceBreakpoints={deviceBreakpoints}
              doc={activeDoc}
              rendererRegistry={rendererRegistry}
            />
          )
        )}
      </main>
    </div>
  )
}

function normalizeStyleguideDocs(docs?: ComponentDocsSource): NormalizedComponentDoc[] {
  return docs ? normalizeDocs(docs) : []
}

// packages/styleguide-viewer-vue/src/components/StyleguideContainer.vue
<template>
  <div class="styleguide-container">
    <nav v-if="effectiveDocs.length > 0" class="styleguide-nav">
      <p class="styleguide-nav-label">Components</p>
      <div class="nav-tabs">
        <button
          v-for="(doc, index) in effectiveDocs"
          :key="`${doc.id}-${index}`"
          :class="navTabClass(index)"
          @click="activeDocIndex = index"
        >
          <span class="nav-tab-dot" aria-hidden="true"></span>
          <span class="nav-tab-copy">
            <span class="nav-tab-title">{{ doc.title }}</span>
            <span class="nav-tab-framework">{{ doc.framework }}</span>
          </span>
        </button>
      </div>
    </nav>

    <main class="styleguide-content">
      <div v-if="effectiveDocs.length === 0" class="no-docs">
        <h2>문서가 없습니다</h2>
        <p>문서를 추가해주세요. (로드된 문서: {{ injectedDocs.length }}개)</p>
      </div>
      <WidgetComponentDoc
        v-else-if="activeDoc"
        :component="activeDoc.component"
        :device-breakpoints="deviceBreakpoints"
        :doc="activeDoc"
      />
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, ref, watch } from 'vue'
import type { ComponentDocsSource, NormalizedComponentDoc } from 'styleguide-schema'
import { normalizeDocs } from 'styleguide-core'
import { StyleguideDocsKey } from '../symbols'
import type { Device } from '../composables/useDevicePreview'
import WidgetComponentDoc from './ComponentDoc.vue'

interface Props {
  docs?: ComponentDocsSource
  deviceBreakpoints?: Record<Exclude<Device, 'custom'>, number>
}

const props = withDefaults(defineProps<Props>(), {
  deviceBreakpoints: () => ({
    mobile: 375,
    tablet: 768,
    desktop: 1200,
  }),
})

const injectedDocs = inject<NormalizedComponentDoc[]>(StyleguideDocsKey, [])
const activeDocIndex = ref(0)

const effectiveDocs = computed(() => {
  if (props.docs) {
    return normalizeDocs(props.docs)
  }

  return injectedDocs
})

const activeDoc = computed(() => effectiveDocs.value[activeDocIndex.value] ?? effectiveDocs.value[0])

watch(effectiveDocs, docs => {
  if (docs.length === 0) {
    activeDocIndex.value = 0
    return
  }

  if (activeDocIndex.value >= docs.length) {
    activeDocIndex.value = 0
  }
}, { immediate: true })

const navTabClass = (index: number) => ['nav-tab', { 'nav-tab--active': activeDocIndex.value === index }]
</script>
